### ISSUE TITLE
[Bug] Profile is only partially in sync with JSON card

### ISSUE THREAD

**Issue by MartinZikmund** [WeAreDotnet/dotnet-creator-cards#244]
**Describe the bug**

My JSON card contains:

- Three channels
- Two RSS feeds

On the side I only see one channel and one feed. In addition, it seems the URLs are outdated (I have switched from blog.mzikmund.com to mzikmund.dev/blog). Other content seems to be updating correctly though, so it is confusing.

In addition, the YouTube RSS feed content does not show up on my profile nor on the main page.

**To Reproduce**
1. Go to my profile on https://www.wearedotnet.io/MartinZikmund
2. Compare to https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/martin-zikmund.json
3. Also note that even new articles like my C# Advent blogpost don't show up in https://www.wearedotnet.io/content or on profile - so the RSS feed seems to be same old cached version

**Expected behavior**

Should by in sync with actual data source.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinZikmund** [comment]
@matthiasjost any chance I could help out investigate and contribute a fix please?

**Comment by matthiasjost** [comment]
Let us ask @DeeJayTC 👋

**Comment by DeeJayTC** [comment]
Habe to get some christmas shopping dond but ill check it later today, @MartinZikmund can you make sure that the data in master branch for your card is correct and your feed doesnt have any errors?

**Comment by DeeJayTC** [comment]
Can you check your profile @MartinZikmund should be fine now :) needed some loving hand to re-sync properly :)

**Comment by MartinZikmund** [comment]
@DeeJayTC almost there 😅 !

- The YouTube feed now shows up on my profile card ✅
- My newest published video showed up on home page ✅
- Previous YouTube videos do not show up on home page ❌ (I published quite a few since start of December)
- 2022 blogposts show up in my profile card ✅
- Newer blogposts don't show up on the profile card ❌ (published two in December)
- Newer blogposts don't show up on home page ❌

Maybe it could be that both feeds are called "dotnet"? Or maybe I am missing something else still 😓

**Comment by DeeJayTC** [comment]
Hmm no...i need to check. Youtube feeds are weird as in it sometimes only shows the last 20 vids i think so i cant get older ones. 

Regarding your blog ill check nut wait till tomorrow as i changed a few things manually cache might not have caught up just yet.

**Comment by DeeJayTC** [comment]
I probably still have your private one listed as i dont reping them once added 😞😞

**Comment by MartinZikmund** [comment]
> Hmm no...i need to check. Youtube feeds are weird as in it sometimes only shows the last 20 vids i think so i cant get older ones.
> 
> Regarding your blog ill check but wait till tomorrow as i changed a few things manually cache might not have caught up just yet.

Actually the main page feed does not contain any of my videos, even the most recent ones (while the profile card feed does) 👀

**Comment by DeeJayTC** [comment]
Yea, the main page feed is fed by Azure Search which did not contain your things for whatever reason, after resync it also had your private video..yay, its resyncing right now....should all be fine within the next 20 minutes or so, can you give it a look later? @MartinZikmund if stuff is still not ok we have to wait until january tho as i wont have access to things for 3 weeks.

**Comment by DeeJayTC** [comment]
Your Advent Of Code Day 16 is the last one on the frontpage now

**Comment by MartinZikmund** [comment]
For now it seems things are working correctly, thanks again!

**Comment by MartinZikmund** [comment]
@DeeJayTC  Unfortunately have to reopen 😥 . I created a new blogpost and two videos on YouTube this week and so far none of these has showed up on the site feed, I still see the old Advent of Code video (and I have published quite a few of them since)

**Comment by DeeJayTC** [comment]
Sorry for the long delay here....had to spent all my time elsewhere, i'll check it :)

**Comment by samtrion** [comment]
@DeeJayTC @matthiasjost 

I’m encountering a very similar issue: I’m not listed as a creator, and my blog posts are not being correctly indexed. Over the past 10 days I’ve published 3 blog posts — only one of them appears on the site.

Happy to provide my JSON card, RSS feed links or any other details required to help investigate.
